# Generated by Django 5.2.7 on 2025-11-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField()),
                ('actual_label', models.CharField(blank=True, max_length=50, null=True)),
                ('image_data', models.TextField()),
                ('draw_by', models.CharField(default='Canvas', max_length=20)),
                ('inference_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
